# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "b094cf4b-67d2-4a62-ab8d-f6466eff8bb4"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  cocoapods

  # build your iOS app
  gym(
    scheme: "IMeditated"
  )

  # upload to Testflight
  pilot(skip_waiting_for_build_processing: true)
end

lane :release do
    increment_build_number
    gym(scheme: "IMeditated") # Build your app - more options available

    snapshot
    # frameit(white: true, path: './fastlane/screenshots')

    deliver(force: true)
end